name       : kdev-python
version    : 5.5.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.5.2/src/kdev-python-5.5.2.tar.xz : 2e70249e48eb1c5720a3304761454b0d203bfec9473121dd0d25b977a91f7edc
license    : LGPL-2.0
component  : programming.tools
summary    : Python support for KDevelop
description: |
    KDevelop plugin which provides Python language support.
libsplit   : no
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Core)
    - kdevelop-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
