name       : kdev-python
version    : 5.4.5
release    : 10
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.4.5/src/kdev-python-5.4.5.tar.xz : a8469886df9a81f3f16db31474a9ed440b1a60224eb28505b5ac63479ad45812
license    : LGPL-2.0
component  : programming.tools
libsplit   : no
summary    : Python support for KDevelop
description: |
    KDevelop plugin which provides Python language support.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kdevelop-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
