name       : kdev-python
version    : 5.2.4
release    : 3
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.2.4/src/kdev-python-5.2.4.tar.xz : 45394fac8fd6cef6d5dfd310afb6184f71660dbcffeaa7de121f04da2e293eba
license    : LGPL-2.0
component  : programming.tools
libsplit   : no
summary    : Python support for KDevelop
description: |
    KDevelop plugin which provides Python language support.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python3)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kdevelop-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
